#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Mustdie 10' {
	search --fs-uuid --no-floppy --set=root A85E-0531
	chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}
